[package]
name = "GameBarrels"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
serde_json = "1.0"
serde = "1.0"
uuid = "0.8.2"
